/// <mls fileReference="_102035_/l1/pizzaria/persistence.ts" enhancement="_blank" />
import type { TableDefinition } from '/_102034_/l1/server/layer_1_external/persistence/contracts.js';

export const tableDefinitions: TableDefinition[] = [
  {
    moduleId: 'pizzaria',
    repositoryName: 'pizzariaPedido',
    tableName: 'Pedido',
    purpose: 'cadastro',
    description: 'Registro central do pedido do cliente.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'status', postgresType: 'TEXT' },
      { name: 'criadoEm', postgresType: 'TIMESTAMPTZ' },
      { name: 'atualizadoEm', postgresType: 'TIMESTAMPTZ' },
      { name: 'itens', postgresType: 'TEXT' },
      { name: 'responsavelAtendimento', postgresType: 'TEXT' },
      { name: 'observacoes', postgresType: 'TEXT' },
      { name: 'formaPagamento', postgresType: 'TEXT' },
      { name: 'statusPagamento', postgresType: 'TEXT' },
      { name: 'observacaoCritica', postgresType: 'TEXT' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_Pedido_status', columns: ['status'] },
      { name: 'idx_Pedido_criadoEm', columns: [{ name: 'criadoEm', direction: 'desc' }] },
      { name: 'idx_Pedido_atualizadoEm', columns: [{ name: 'atualizadoEm', direction: 'desc' }] },
      { name: 'idx_Pedido_statusPagamento', columns: ['statusPagamento'] },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'Pedido_documents',
        staging: 'Pedido_documents_test',
        production: 'Pedido_documents',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
  {
    moduleId: 'pizzaria',
    repositoryName: 'pizzariaItemPedido',
    tableName: 'ItemPedido',
    purpose: 'cadastro',
    description: 'Item individual de um pedido.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'pedidoId', postgresType: 'TEXT' },
      { name: 'nome', postgresType: 'TEXT' },
      { name: 'quantidade', postgresType: 'INTEGER' },
      { name: 'observacoes', postgresType: 'TEXT' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_ItemPedido_pedidoId', columns: ['pedidoId'] },
      { name: 'idx_ItemPedido_quantidade', columns: [{ name: 'quantidade', direction: 'desc' }] },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'ItemPedido_documents',
        staging: 'ItemPedido_documents_test',
        production: 'ItemPedido_documents',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
  {
    moduleId: 'pizzaria',
    repositoryName: 'pizzariaProducao',
    tableName: 'Producao',
    purpose: 'cadastro',
    description: 'Controle do processo de produção na cozinha.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'pedidoId', postgresType: 'TEXT' },
      { name: 'statusProducao', postgresType: 'TEXT' },
      { name: 'inicioEm', postgresType: 'TIMESTAMPTZ' },
      { name: 'fimEm', postgresType: 'TIMESTAMPTZ' },
      { name: 'cozinheiroResponsavelId', postgresType: 'TEXT' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_Producao_pedidoId', columns: ['pedidoId'] },
      { name: 'idx_Producao_statusProducao', columns: ['statusProducao'] },
      { name: 'idx_Producao_inicioEm', columns: [{ name: 'inicioEm', direction: 'desc' }] },
      { name: 'idx_Producao_fimEm', columns: [{ name: 'fimEm', direction: 'desc' }] },
      { name: 'idx_Producao_cozinheiroResponsavelId', columns: ['cozinheiroResponsavelId'] },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'Producao_documents',
        staging: 'Producao_documents_test',
        production: 'Producao_documents',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
  {
    moduleId: 'pizzaria',
    repositoryName: 'pizzariaEntrega',
    tableName: 'Entrega',
    purpose: 'cadastro',
    description: 'Controle da entrega do pedido.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'pedidoId', postgresType: 'TEXT' },
      { name: 'entregadorId', postgresType: 'TEXT' },
      { name: 'statusEntrega', postgresType: 'TEXT' },
      { name: 'inicioEm', postgresType: 'TIMESTAMPTZ' },
      { name: 'fimEm', postgresType: 'TIMESTAMPTZ' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_Entrega_pedidoId', columns: ['pedidoId'] },
      { name: 'idx_Entrega_entregadorId', columns: ['entregadorId'] },
      { name: 'idx_Entrega_statusEntrega', columns: ['statusEntrega'] },
      { name: 'idx_Entrega_inicioEm', columns: [{ name: 'inicioEm', direction: 'desc' }] },
      { name: 'idx_Entrega_fimEm', columns: [{ name: 'fimEm', direction: 'desc' }] },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'Entrega_documents',
        staging: 'Entrega_documents_test',
        production: 'Entrega_documents',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
  {
    moduleId: 'pizzaria',
    repositoryName: 'pizzariaUsuario',
    tableName: 'Usuario',
    purpose: 'cadastro',
    description: 'Usuário interno do sistema.',
    backupHot: true,
    storageProfile: 'postgresHotBackup',
    writeMode: 'writeBehind',
    columns: [
      { name: 'id', postgresType: 'TEXT' },
      { name: 'nome', postgresType: 'TEXT' },
      { name: 'perfil', postgresType: 'TEXT' },
    ],
    primaryKey: ['id'],
    indexes: [
      { name: 'idx_Usuario_perfil', columns: ['perfil'] },
    ],
    dynamo: {
      tableNameByEnv: {
        development: 'Usuario_documents',
        staging: 'Usuario_documents_test',
        production: 'Usuario_documents',
      },
      partitionKey: 'id',
    },
    version: 1,
  },
];